<tr class="HEADER" vAlign="bottom">
<th align="left">Last Name</th>
<th align="left">First Name<br /></th>
<th align="left">Regular&nbsp;&nbsp;<br />Hours</th>
<th align="left">Double&nbsp;&nbsp;<br />Time<br />Hours</th>
<th align="left">Over&nbsp;&nbsp;<br />Time<br />Hours</th>
<th align="left">Vacation<br />Time</th>
<th align="left">Sick<br />Time&nbsp;&nbsp;&nbsp;&nbsp;</th>
<th align="left">Holiday&nbsp;<br />Time</th>
<th align="left">Funeral&nbsp;<br />Time</th>
<th align="left">Total Hours<br />Worked</th>
<th align="left">&nbsp;</th>
<th align="left"><br />&nbsp;</th>